name: Publish to npm on Merge to Master
env:
  PACKAGE_NAME: "salat"

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check if package version changed
        id: check_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          LAST_PUBLISHED_VERSION=$(npm show ${{ env.PACKAGE_NAME }} version)
          if [ "$CURRENT_VERSION" == "$LAST_PUBLISHED_VERSION" ]; then
            echo "version_changed=false" >> $GITHUB_ENV
            exit 1
          else
          echo "version_changed=true" >> $GITHUB_ENV
          fi
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci --production
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
